version: "3.8"
services:
  server:
    container_name: service-one
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:9001"
    networks:
      springboot-mysql-net:
    restart: on-failure
networks:
  springboot-mysql-net: