name:  Main

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
    # Cũng trigger khi page_build, cũng như release created events
    page_build:
    release:
      types: # Cấu hình này không ảnh hưởng đến events page_build ở trên
        - created
publish:
  name: Install and publish
  runs-on: ubuntu-latest

step:
  # Kiểm tra kho lưu trữ của bạn dưới $ GITHUB_WORKSPACE, để công việc của bạn có thể truy cập nó
  - uses: actions/checkout@v2

  # Chạy một lệnh đơn bằng cách sử dụng trình bao của người chạy
  - name: Run a one-line script
    run: echo Hello, world!
    with:
      node-version: 12.x
  - uses: expo/expo-github-action@v5
    with:
      expo-version: 3.x
      expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
      expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
